// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideItem: typeof import('./../components/base/asideItem.vue')['default']
    BaseItem: typeof import('./../components/base/baseItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeaderItem: typeof import('./../components/base/headerItem.vue')['default']
    'ICarbon:task': typeof import('~icons/carbon/task')['default']
    IconItem: typeof import('./../components/base/options/iconItem.vue')['default']
    'IEp:user': typeof import(../components/base/options/iconItem.vue
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    'IIc:baselineGroup': typeof import('~icons/ic/baseline-group')['default']
    'IIc:carbon:task': typeof import('~icons/ic/carbon-task')['default']
    'IMaterialSymbols:3p': typeof import('~icons/material/symbols-3p')['default']
    IndexItem: typeof import("../components/LoginRegistration/loginRegistrationItem.vue")["default"]
    LoginForm: typeof import('./../components/LoginRegistration/loginForm.vue')['default']
    LoginRegistrationItem: typeof import('./../components/LoginRegistration/loginRegistrationItem.vue')['default']
    MainItem: typeof import('./../components/base/mainItem.vue')['default']
    OptionCard: typeof import('../components/base/aside/optionItem.vue')['default']
    OptionItem: typeof import('./../components/base/optionItem.vue')['default']
    RegisterForm: typeof import('./../components/LoginRegistration/registerForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIcon: typeof import('./../components/LoginRegistration/icons/userIcon.vue')['default']
  }
}
