// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddGroupItem: typeof import('./../components/MainPage/aside/group/addGroupItem.vue')['default']
    AsideGroupInfoItem: typeof import('../components/MainPage/aside/group/groupInfoItem.vue')['default']
    AsideGroupItem: typeof import('./../components/MainPage/aside/group/asideGroupItem.vue')['default']
    AsideHeaderItem: typeof import('./../components/MainPage/aside/base/asideHeaderItem.vue')['default']
    AsideInfoItem: typeof import('./../components/MainPage/aside/base/asideInfoItem.vue')['default']
    AsideItem: typeof import('./../components/MainPage/base/asideItem.vue')['default']
    AsideMainItem: typeof import('./../components/MainPage/aside/base/asideMainItem.vue')['default']
    AsideTaskItem: typeof import('./../components/MainPage/aside/task/asideTaskItem.vue')['default']
    ChatBox: typeof import('./../components/MainPage/main/chatBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GroupImageClip: typeof import('./../components/MainPage/aside/group/groupImageClip.vue')['default']
    GroupInfoItem: typeof import('./../components/MainPage/aside/group/groupInfoItem.vue')['default']
    HeaderItem: typeof import('./../components/MainPage/base/headerItem.vue')['default']
    'ICarbon:userAvatarFilled': typeof import('~icons/carbon/user-avatar-filled')['default']
    IconItem: typeof import('./../components/MainPage/option/iconItem.vue')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    'IIc:baselineAdd': typeof import('~icons/ic/baseline-add')['default']
    'IIc:baselineDensityMedium': typeof import('~icons/ic/baseline-density-medium')['default']
    'IIc:baselineGroup': typeof import('~icons/ic/baseline-group')['default']
    'IIc:baselineMoreHoriz': typeof import('~icons/ic/baseline-more-horiz')['default']
    'IIc:ic:baselineGroup': typeof import('~icons/ic/ic-baseline-group')['default']
    'IIc:roundRefresh': typeof import('~icons/ic/round-refresh')['default']
    'IIc:roundSearch': typeof import('~icons/ic/round-search')['default']
    'IIc:twotoneGroup': typeof import('~icons/ic/twotone-group')['default']
    LoginFormItem: typeof import('./../components/LoginRegistration/loginFormItem.vue')['default']
    LoginRegistrationItem: typeof import('./../components/LoginRegistration/loginRegistrationItem.vue')['default']
    MainItem: typeof import('./../components/MainPage/base/mainItem.vue')['default']
    MainPageItem: typeof import('./../components/MainPage/mainPageItem.vue')['default']
    OptionItem: typeof import('./../components/MainPage/base/optionItem.vue')['default']
    RegisterFormItem: typeof import('./../components/LoginRegistration/registerFormItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
